x-kafka-common: &kafka-common
  image: apache/kafka:latest
  networks:
    - kafka_network

x-kafka-common-env: &kafka-common-env
  KAFKA_KRAFT_CLUSTER_ID: ZYvV63LYRpucAGWJf9d9nQ
  KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka0:9093,1@kafka1:9093,2@kafka2:9093
  ALLOW_PLAINTEXT_LISTENER: "yes"
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
  KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
  KAFKA_PROCESS_ROLES: controller,broker
  KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

services:
  kafka0:
    <<: *kafka-common
    ports:
      - "10000:9094"
    environment:
      <<: *kafka-common-env
      KAFKA_BROKER_ID: 0
      KAFKA_NODE_ID: 0
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka0:9092,EXTERNAL://127.0.0.1:10000
    volumes:
      - ./kafka0_data:/var/lib/kafka
    healthcheck:
      test: ["CMD", "/opt/kafka/bin/kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 10s
      retries: 10

  kafka1:
    <<: *kafka-common
    ports:
      - "10001:9094"
    environment:
      <<: *kafka-common-env
      KAFKA_BROKER_ID: 1
      KAFKA_NODE_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,EXTERNAL://127.0.0.1:10001
    volumes:
      - ./kafka1_data:/var/lib/kafka
    healthcheck:
      test: ["CMD", "/opt/kafka/bin/kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 10s
      retries: 10

  kafka2:
    <<: *kafka-common
    ports:
      - "10002:9094"
    environment:
      <<: *kafka-common-env
      KAFKA_BROKER_ID: 2
      KAFKA_NODE_ID: 2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092,EXTERNAL://127.0.0.1:10002
    volumes:
      - ./kafka2_data:/var/lib/kafka
    healthcheck:
      test: ["CMD", "/opt/kafka/bin/kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 10s
      retries: 10

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "19000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka0:9092,kafka1:9092,kafka2:9092
      SERVER_PORT: 9000
    depends_on:
      - kafka0
      - kafka1
      - kafka2
    networks:
      - kafka_network

  python-producer:
    build: ./producer
    depends_on:
      kafka0:
        condition: service_healthy
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
    networks:
      - kafka_network

networks:
  kafka_network:
    driver: bridge

volumes:
  kafka0_data:
    driver: local
  kafka1_data:
    driver: local
  kafka2_data:
    driver: local